name: Mike Partridge
favicon: null
layout_spectrum: 0.47869875957258046
typography_spectrum: 0.5049539564643055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#7e7e7e'
    - '#575757'
    - '#c1c1c1'
    - '#e3e3e3'
  brandStrength: 0.3125
  lightness: 0.748442801181227
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
